import os
import re
from fpdf import FPDF

def generate_pdf_report(metrics, logs, incidents, ai_analysis_text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # --- 1. Initialize variables safely at the top to prevent scoping errors ---
    recent_anomalies = 0
    total_records = len(metrics) if not metrics.empty else 0
    critical_logs = logs[logs['log_level'] == 'CRITICAL'].shape[0] if not logs.empty else 0
    high_incidents = incidents[incidents['severity'] == 'High'].shape[0] if not incidents.empty else 0

    # --- 2. Calculate Health Score ---
    if not metrics.empty and 'is_anomaly' in metrics.columns:
        # Ensure boolean type
        if metrics['is_anomaly'].dtype == 'object':
            metrics['is_anomaly'] = metrics['is_anomaly'].astype(str).str.lower() == 'true'
        recent_anomalies = metrics[metrics['is_anomaly'] == True].shape[0]

    # Percentage-based score (Realistic)
    anomaly_pct = (recent_anomalies / total_records) * 100 if total_records > 0 else 0
    health_score = max(0, 100 - (anomaly_pct * 2))

    # Determine Score Color and Text
    if health_score >= 80:
        score_color = (39, 174, 96) # Green
        score_text = "HEALTHY"
    elif health_score >= 50:
        score_color = (243, 156, 18) # Orange
        score_text = "WARNING"
    else:
        score_color = (192, 57, 43) # Red
        score_text = "CRITICAL"

    # --- 3. Header ---
    pdf.set_fill_color(41, 128, 185)
    pdf.rect(0, 0, 210, 40, 'F')
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 12)
    pdf.cell(0, 10, 'Legacy System Health Report', ln=True, align='C')
    pdf.set_font('Helvetica', '', 10)
    pdf.set_xy(10, 25)
    pdf.cell(0, 8, 'Generated by TCS AI Health Monitor', ln=True, align='C')
    pdf.ln(25)

    # --- 4. Health Score Badge ---
    pdf.set_fill_color(*score_color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 12, f'Health Score: {health_score:.0f}/100 - {score_text}', ln=True, align='C', fill=True)
    pdf.ln(10)

    # --- 5. KPI Cards ---
    pdf.set_text_color(44, 62, 80)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(60, 10, f'Critical Alerts: {critical_logs}', border=1, align='C')
    pdf.cell(65, 10, f'High Incidents: {high_incidents}', border=1, align='C')
    pdf.cell(60, 10, f'Anomalies: {recent_anomalies}', border=1, align='C', ln=True)
    pdf.ln(10)

    # --- 6. AI Analysis Section ---
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 10, 'AI Analysis & Recommendations', ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # Clean markdown text for PDF
    clean_text = re.sub(r'#+\s*', '', ai_analysis_text)
    clean_text = re.sub(r'---+', '', clean_text)
    clean_text = re.sub(r'\*\*(.*?)\*\*', r'\1', clean_text) 
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(52, 73, 94)
    
    for line in clean_text.split('\n'):
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue
        if line.endswith(':') or re.match(r'^\d+\.', line):
            pdf.set_font('Helvetica', 'B', 11)
            pdf.set_text_color(44, 62, 80)
            pdf.multi_cell(0, 6, line)
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(52, 73, 94)
        elif line.startswith('-'):
            pdf.set_x(15)
            pdf.multi_cell(0, 5, f"• {line[1:].strip()}")
        else:
            pdf.multi_cell(0, 5, line)

    # --- 7. Save PDF ---
    output_path = "data/Legacy_System_Health_Report.pdf"
    os.makedirs("data", exist_ok=True)
    pdf.output(output_path)
    return output_path