import os
import re
from fpdf import FPDF

def remove_emojis(text):
    """Helper function to remove emojis since standard FPDF fonts don't support them."""
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags (iOS)
        "]+", flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

def generate_pdf_report(metrics, logs, incidents, ai_analysis_text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- Title ---
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Legacy System Health Report", ln=True, align="C")
    pdf.ln(5)
    
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 5, "Generated by TCS AI Health Monitor", ln=True, align="C")
    pdf.ln(10)

    # --- Section 1: KPI Summary ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "1. System KPIs", ln=True)
    pdf.set_font("Helvetica", "", 10)
    
    # Calculate KPIs
    if 'is_anomaly' in metrics.columns:
        if metrics['is_anomaly'].dtype == 'object':
            metrics['is_anomaly'] = metrics['is_anomaly'].astype(str).str.lower() == 'true'
        recent_anomalies = metrics[metrics['is_anomaly'] == True].shape[0]
    else:
        recent_anomalies = 0
        
    health_score = max(0, 100 - (recent_anomalies * 0.5))
    critical_logs = logs[logs['log_level'] == 'CRITICAL'].shape[0]
    high_incidents = incidents[incidents['severity'] == 'High'].shape[0]

    pdf.cell(0, 6, f"- Overall Health Score: {health_score:.1f} / 100", ln=True)
    pdf.cell(0, 6, f"- Total Critical Alerts: {critical_logs}", ln=True)
    pdf.cell(0, 6, f"- High Priority Incidents: {high_incidents}", ln=True)
    pdf.ln(5)

    # --- Section 2: AI Insights ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "2. AI-Driven Insights & Maintenance Priorities", ln=True)
    pdf.set_font("Helvetica", "", 9)
    
    # Clean text for PDF (remove emojis and markdown asterisks for cleaner look)
    clean_text = remove_emojis(ai_analysis_text)
    clean_text = clean_text.replace("**", "").replace("###", "").replace("##", "").replace("#", "")
    
    pdf.multi_cell(0, 5, clean_text)
    pdf.ln(10)

    # --- Footer ---
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 10, "Confidential - For Internal IT Maintenance Use Only", ln=True, align="C")

    # --- Save and return path ---
    output_path = "data/System_Health_Report.pdf"
    os.makedirs("data", exist_ok=True)
    pdf.output(output_path)
    return output_path